version: "3.2"
services:
  sql-server-db:
    container_name: azure-sql
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SA_PASSWORD"
      ACCEPT_EULA: "Y"